name: Send Email Notification
on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        env:
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          API_KEY: ${{ secrets.API }}
        run: |
          echo "Sending email from $GMAIL_SENDER"
          python /SiteEye/blob/main/site_eye.py
